name: cron

on:
  schedule:
    - cron: "0 10 * * MON"

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:   
      - name: auto build image
        uses: benc-uk/workflow-dispatch@e2e5e9a103e331dad343f381a29e654aea3cf8fc
        with:
          workflow: docker.yml